include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - always_use_package_imports
    - package_names
    - require_trailing_commas
    - lines_longer_than_80_chars

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  # https://github.com/rrouselGit/freezed/issues/488#issuecomment-894358980
  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameters-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 5
    #source-lines-of-code: 50
    metrics-exclude:
      test/**
  rules:
    - avoid-returning-widgets:
      ignored-names:
        - testFunction
    - ignored-annotations:
        allowedAnnotation
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-shrink-wrap-in-lists
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - member-ordering:
      widgets-order:
        - constructor
        - named-constructor
        - const-fields
        - static-methods
        - final-fields
        - init-state-method
        - var-fields
        - init-state-method
        - private-methods
        - overridden-public-methods
        - build-method

    - always-remove-listener
    - avoid-wrapping-in-padding
    - avoid-expanded-as-spacer
