name: password_manager
description: A new Flutter project.
publish_to: 'none'

version: 1.8.0+13

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.0
  go_router: ^14.3.0

  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4

  flutter_secure_storage: ^9.2.2
  local_auth: ^2.1.6
  focus_detector: ^2.0.1

  path_provider: ^2.1.4
  file_picker: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.6

  analyzer: ^5.13.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Verdana
      fonts:
        - asset: assets/fonts/Verdana.ttf
